server:
  port: 8086
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8、
  data:
    #配置elasticSearch信息
    elasticsearch:
      #连接的集群名称
      cluster-name: my-application
      #连接的集群节点
      cluster-nodes: localhost:9300
      #是否开启本地储存
      repositories:
        enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1:3306/20068?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

